<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5d6d8bec21122',
	'title' => 'FLEX: Calendar',
	'fields' => array(
		array(
			'key' => 'field_5d6d9033efd88',
			'label' => 'Title',
			'name' => 'title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '75',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'acfe_validate' => '',
			'acfe_update' => '',
		),
		array(
			'key' => 'field_5d834ca14de1c',
			'label' => 'Calendar list type',
			'name' => 'calendar_list_type',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'choices' => array(
				'tile' => 'Tiled',
				'list' => 'List',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'acfe_validate' => '',
			'acfe_update' => '',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5d6d8bf8f71d7',
			'label' => 'Number of calendar dates to show',
			'name' => 'number_of_dates',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'choices' => array(
				100 => 'All',
				3 => 'Three',
				6 => 'Six',
				9 => 'Nine',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'acfe_validate' => '',
			'acfe_update' => '',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5d6d9881adaf8',
			'label' => 'Hide calendar navigation',
			'name' => 'hide_calendar_navigation',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'acfe_validate' => '',
			'acfe_update' => '',
		),
		array(
			'key' => 'field_5d83563df9a1f',
			'label' => 'Hide search',
			'name' => 'hide_search',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'acfe_validate' => '',
			'acfe_update' => '',
		),
		array(
			'key' => 'field_5d8368c152f4a',
			'label' => 'Hide module if empty',
			'name' => 'hide_module_if_empty',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'acfe_validate' => '',
			'acfe_update' => '',
		),
		array(
			'key' => 'field_5d836a463c604_field_5d836b1d344d1',
			'label' => 'BG Colours',
			'name' => 'background_colours_basic',
			'type' => 'color_palette',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'choices' => array(
				'#ffffff' => 'White',
				'#F8F8F8' => 'Grey',
			),
			'default_value' => '#ffffff',
			'return_format' => 'value',
			'acfe_validate' => '',
			'acfe_update' => '',
			'readonly' => 'readonly',
			'_clone' => 'field_5d836a463c604',
			'__key' => 'field_5d836b1d344d1',
			'__name' => 'background_colours_basic',
			'__label' => 'BG Colours',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 58,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_permissions' => '',
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1611658199,
));

endif;