<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5d7f85b205bda',
	'title' => 'FLEX: Hero 01',
	'fields' => array(
		array(
			'key' => 'field_5d7f85b20f04c',
			'label' => 'Carousel slides',
			'name' => 'carousel_slides',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'collapsed' => '',
			'min' => 1,
			'max' => 0,
			'layout' => 'row',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5d7f85b210623',
					'label' => 'Content',
					'name' => 'content',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5d7f85b21192c',
							'label' => 'Title',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'acfe_validate' => '',
							'acfe_update' => '',
						),
						array(
							'key' => 'field_5d7f85b21193a',
							'label' => 'Paragraph',
							'name' => 'paragraph',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'tabs' => 'visual',
							'toolbar' => 'basic',
							'media_upload' => 0,
							'delay' => 0,
							'acfe_validate' => '',
							'acfe_update' => '',
						),
						array(
							'key' => 'field_5d7f85b211942',
							'label' => 'Link',
							'name' => 'link',
							'type' => 'link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'return_format' => 'array',
							'acfe_validate' => '',
							'acfe_update' => '',
						),
					),
				),
				array(
					'key' => 'field_5d7f85b217e80',
					'label' => 'Media',
					'name' => 'media',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5d7f85b219192',
							'label' => 'Message',
							'name' => '',
							'type' => 'message',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'message' => 'Using more images will give better results when in smaller screens but will also reduce page speed load times.',
							'new_lines' => 'wpautop',
							'esc_html' => 0,
						),
						array(
							'key' => 'field_5d7f85b21919f',
							'label' => 'Desktop Image',
							'name' => 'desktopImage',
							'type' => 'image_aspect_ratio_crop',
							'instructions' => '3840 × 2160',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'aspect_ratio_width' => 3840,
							'aspect_ratio_height' => 2160,
							'return_format' => 'array',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'acfe_validate' => '',
							'acfe_update' => '',
							'crop_type' => 'aspect_ratio',
						),
						array(
							'key' => 'field_5d7f85b2191a9',
							'label' => 'Tablet Image',
							'name' => 'tabletImage',
							'type' => 'image_aspect_ratio_crop',
							'instructions' => '1668x2224',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'aspect_ratio_width' => 1668,
							'aspect_ratio_height' => 2224,
							'return_format' => 'array',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'acfe_validate' => '',
							'acfe_update' => '',
							'crop_type' => 'aspect_ratio',
						),
						array(
							'key' => 'field_5d7f85b2191b5',
							'label' => 'Mobile Image',
							'name' => 'mobileImage',
							'type' => 'image_aspect_ratio_crop',
							'instructions' => '828x1792',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'aspect_ratio_width' => 828,
							'aspect_ratio_height' => 1792,
							'return_format' => 'array',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'acfe_validate' => '',
							'acfe_update' => '',
							'crop_type' => 'aspect_ratio',
						),
						array(
							'key' => 'field_5d7f85b2191bf',
							'label' => 'Overlay opacity',
							'name' => 'overlay_opacity',
							'type' => 'range',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => 9,
							'min' => 0,
							'max' => 9,
							'step' => '',
							'prepend' => '',
							'append' => '',
							'acfe_validate' => '',
							'acfe_update' => '',
						),
					),
				),
			),
		),
		array(
			'key' => 'field_5d9dbc18d46bb_field_5db1cbd9c9064',
			'label' => 'Hero decal overlay',
			'name' => 'hero_decal_overlay',
			'type' => 'image_aspect_ratio_crop',
			'instructions' => 'Ratio: 928x928 for best results',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'aspect_ratio_width' => 928,
			'aspect_ratio_height' => 928,
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'acfe_validate' => '',
			'acfe_update' => '',
			'_clone' => 'field_5d9dbc18d46bb',
			'__key' => 'field_5db1cbd9c9064',
			'__name' => 'hero_decal_overlay',
			'__label' => 'Hero decal overlay',
			'crop_type' => 'aspect_ratio',
		),
		array(
			'key' => 'field_5d9dbc18d46bb_field_5dbd93b93aff6',
			'label' => 'Page down icon',
			'name' => 'page_down_icon',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'choices' => array(
				'chevron' => 'Chevron Down',
				'mouse' => 'Mouse wheel',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'acfe_validate' => '',
			'acfe_update' => '',
			'save_other_choice' => 0,
			'_clone' => 'field_5d9dbc18d46bb',
			'__key' => 'field_5dbd93b93aff6',
			'__name' => 'page_down_icon',
			'__label' => 'Page down icon',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 52,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_permissions' => '',
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1611658188,
));

endif;