<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5d80ff4e2b007',
	'title' => 'Flexible content - page content',
	'fields' => array(
		array(
			'acfe_flexible_advanced' => 1,
			'acfe_flexible_stylised_button' => 1,
			'acfe_flexible_hide_empty_message' => 0,
			'acfe_flexible_empty_message' => '',
			'acfe_flexible_disable_ajax_title' => 0,
			'acfe_flexible_layouts_thumbnails' => 1,
			'acfe_flexible_layouts_settings' => 0,
			'acfe_flexible_layouts_ajax' => 0,
			'acfe_flexible_layouts_templates' => 0,
			'acfe_flexible_layouts_previews' => 0,
			'acfe_flexible_layouts_placeholder' => 1,
			'acfe_flexible_title_edition' => 1,
			'acfe_flexible_clone' => 0,
			'acfe_flexible_copy_paste' => 1,
			'acfe_flexible_toggle' => 0,
			'acfe_flexible_close_button' => 1,
			'acfe_flexible_remove_add_button' => 0,
			'acfe_flexible_remove_duplicate_button' => 0,
			'acfe_flexible_remove_delete_button' => 0,
			'acfe_flexible_lock' => 0,
			'acfe_flexible_modal_edition' => 0,
			'acfe_flexible_modal' => array(
				'acfe_flexible_modal_enabled' => '1',
				'acfe_flexible_modal_title' => 'Test',
				'acfe_flexible_modal_col' => '4',
				'acfe_flexible_modal_categories' => '1',
			),
			'acfe_flexible_layouts_state' => '',
			'acfe_flexible_layouts_remove_collapse' => 0,
			'key' => 'field_5d80ff4e2fa44',
			'label' => 'Flexible content',
			'name' => 'flexible_content',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'layouts' => array(
				'layout_5d4a7ad361315' => array(
					'key' => 'layout_5d4a7ad361315',
					'name' => 'content-accordion-01',
					'label' => 'Accordion menu',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5e20ee8533f1e',
							'label' => 'Accordion',
							'name' => 'accordion',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'acfe_repeater_stylised_button' => 0,
							'collapsed' => '',
							'min' => 1,
							'max' => 0,
							'layout' => 'row',
							'button_label' => '',
							'sub_fields' => array(
								array(
									'key' => 'field_5e20ee9733f1f',
									'label' => 'Title',
									'name' => 'title',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5e20eef133f20',
									'label' => 'Paragraph',
									'name' => 'paragraph',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 0,
									'delay' => 0,
								),
							),
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => '',
					'acfe_flexible_category' => 'Content',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
				),
				'layout_5d70b289ca16a' => array(
					'key' => 'layout_5d70b289ca16a',
					'name' => 'content-paragraph',
					'label' => 'Paragraph',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5df92e052e2b2',
							'label' => 'Content Clone',
							'name' => 'clone',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'clone' => array(
								0 => 'group_5d4a79d42c77b',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_clone_modal' => 0,
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => '2623',
					'acfe_flexible_category' => 'Content',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
				),
				'layout_5d75216bc0fb8' => array(
					'key' => 'layout_5d75216bc0fb8',
					'name' => 'content-table',
					'label' => 'Table',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5e20d876c3637',
							'label' => 'Content Clone',
							'name' => 'content_clone',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'clone' => array(
								0 => 'group_5d752127a87a6',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_clone_modal' => 0,
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => '',
					'acfe_flexible_category' => 'Content',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
				),
				'layout_5d7529b342695' => array(
					'key' => 'layout_5d7529b342695',
					'name' => 'content-space',
					'label' => 'Space',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5e20d896c3638',
							'label' => 'Content Clone',
							'name' => 'content_clone',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'clone' => array(
								0 => 'group_5d75296f4aa1b',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_clone_modal' => 0,
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => '',
					'acfe_flexible_category' => 'Content',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
				),
				'layout_5d30c216be42d' => array(
					'key' => 'layout_5d30c216be42d',
					'name' => 'content-caro-paragraph-01',
					'label' => 'paragraph carousel 01 ',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5e20d8cdc3639',
							'label' => 'Content Clone',
							'name' => 'content_clone',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'clone' => array(
								0 => 'field_5d30c168ab088',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_clone_modal' => 0,
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => '2613',
					'acfe_flexible_category' => 'Content',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
				),
				'layout_5d49e5f0debd9' => array(
					'key' => 'layout_5d49e5f0debd9',
					'name' => 'content-image',
					'label' => 'Image',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5e20d9341163e',
							'label' => 'Content Clone',
							'name' => 'content_clone',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'clone' => array(
								0 => 'group_5d49e53e4aa8d',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_clone_modal' => 0,
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => '2634',
					'acfe_flexible_category' => 'Content',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
				),
				'layout_5da9e973b6190' => array(
					'key' => 'layout_5da9e973b6190',
					'name' => 'content-image-page',
					'label' => 'Page Content Image ',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5e20d9491163f',
							'label' => 'Content Clone',
							'name' => 'content_clone',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'clone' => array(
								0 => 'group_5da9e90d5913a',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_clone_modal' => 0,
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => '2634',
					'acfe_flexible_category' => 'Content',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
				),
				'layout_5d474e6b4d5d4' => array(
					'key' => 'layout_5d474e6b4d5d4',
					'name' => 'content-title-page-01',
					'label' => 'Title page animation 01',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5e20d96811640',
							'label' => 'Content Clone',
							'name' => 'content_clone',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'clone' => array(
								0 => 'group_5d474e06565f4',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_clone_modal' => 0,
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => '2626',
					'acfe_flexible_category' => 'Content',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
				),
				'layout_5d822455892aa' => array(
					'key' => 'layout_5d822455892aa',
					'name' => 'content-title-01',
					'label' => 'Page title 01',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5e20d99011641',
							'label' => 'Content Clone',
							'name' => 'content_clone',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'clone' => array(
								0 => 'group_5d8220517ceaf',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_clone_modal' => 0,
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => '2626',
					'acfe_flexible_category' => 'Content',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
				),
				'layout_5d4a8ba76f752' => array(
					'key' => 'layout_5d4a8ba76f752',
					'name' => 'policies-pg-01',
					'label' => 'Document List',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5e20d9c711642',
							'label' => 'Content Clone',
							'name' => 'content_clone',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'clone' => array(
								0 => 'group_5d703f3db0296',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_clone_modal' => 0,
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => '2624',
					'acfe_flexible_category' => 'Policies',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
				),
				'layout_5d83397dd0d56' => array(
					'key' => 'layout_5d83397dd0d56',
					'name' => 'cta-link-01',
					'label' => 'CTA - Links 01',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5e20d9ff11643',
							'label' => 'Content Clone',
							'name' => 'content_clone',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'clone' => array(
								0 => 'group_5d6ffb5ba599d',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_clone_modal' => 0,
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => '2624',
					'acfe_flexible_category' => 'CTA',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
				),
				'layout_5d823a3324ce3' => array(
					'key' => 'layout_5d823a3324ce3',
					'name' => 'gallery-pg-02',
					'label' => 'Gallery 02',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5e20da2f11644',
							'label' => 'Content Clone',
							'name' => 'content_clone',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'clone' => array(
								0 => 'group_5d42c9084f29e',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_clone_modal' => 0,
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => '2624',
					'acfe_flexible_category' => 'Gallery',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
				),
			),
			'button_label' => 'Add module',
			'min' => 0,
			'max' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'cpt_page_content',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'cpt_careers',
			),
		),
	),
	'menu_order' => 35,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'discussion',
		3 => 'comments',
		4 => 'author',
		5 => 'format',
		6 => 'page_attributes',
		7 => 'featured_image',
		8 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1611658181,
));

endif;