<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5d80fa0a083c3',
	'title' => 'Flexible content - sidebar',
	'fields' => array(
		array(
			'acfe_flexible_advanced' => 1,
			'acfe_flexible_stylised_button' => 1,
			'acfe_flexible_hide_empty_message' => 0,
			'acfe_flexible_empty_message' => '',
			'acfe_flexible_disable_ajax_title' => 0,
			'acfe_flexible_layouts_thumbnails' => 1,
			'acfe_flexible_layouts_settings' => 0,
			'acfe_flexible_layouts_ajax' => 0,
			'acfe_flexible_layouts_templates' => 0,
			'acfe_flexible_layouts_previews' => 0,
			'acfe_flexible_layouts_placeholder' => 1,
			'acfe_flexible_title_edition' => 0,
			'acfe_flexible_clone' => 0,
			'acfe_flexible_copy_paste' => 1,
			'acfe_flexible_toggle' => 0,
			'acfe_flexible_close_button' => 1,
			'acfe_flexible_remove_add_button' => 0,
			'acfe_flexible_remove_duplicate_button' => 0,
			'acfe_flexible_remove_delete_button' => 0,
			'acfe_flexible_lock' => 0,
			'acfe_flexible_modal_edition' => 1,
			'acfe_flexible_modal' => array(
				'acfe_flexible_modal_enabled' => '1',
				'acfe_flexible_modal_title' => 'Test',
				'acfe_flexible_modal_col' => '4',
				'acfe_flexible_modal_categories' => '1',
			),
			'acfe_flexible_layouts_state' => '',
			'acfe_flexible_layouts_remove_collapse' => 0,
			'key' => 'field_5d80fa0a0c85c',
			'label' => 'Flexible content',
			'name' => 'flexible_content',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'layouts' => array(
				'layout_5d4ac31eece06' => array(
					'key' => 'layout_5d4ac31eece06',
					'name' => 'side-bar-menu-01',
					'label' => 'Side bar Menu 01',
					'display' => 'block',
					'sub_fields' => array(
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => '2620',
					'acfe_flexible_category' => 'Sidebar',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
				),
				'layout_5d775629a3333' => array(
					'key' => 'layout_5d775629a3333',
					'name' => 'side-bar-menu-custom-01',
					'label' => 'Side bar Menu - Custom 01',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5d80fa0a0f19f_field_5d7755e221d5f',
							'label' => 'Title',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'acfe_validate' => '',
							'acfe_update' => '',
							'_clone' => 'field_5d80fa0a0f19f',
							'__key' => 'field_5d7755e221d5f',
							'__name' => 'title',
							'__label' => 'Title',
						),
						array(
							'key' => 'field_5d80fa0a0f19f_field_5d7755e921d60',
							'label' => 'Menu list',
							'name' => 'menu_list',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'collapsed' => '',
							'min' => 0,
							'max' => 0,
							'layout' => 'table',
							'button_label' => '',
							'_clone' => 'field_5d80fa0a0f19f',
							'__key' => 'field_5d7755e921d60',
							'__name' => 'menu_list',
							'__label' => 'Menu list',
							'sub_fields' => array(
								array(
									'key' => 'field_5d77ea80eef62',
									'label' => 'Link type',
									'name' => 'link_type',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'message' => '',
									'default_value' => 0,
									'ui' => 1,
									'ui_on_text' => 'External',
									'ui_off_text' => 'Internal',
									'acfe_validate' => '',
									'acfe_update' => '',
								),
								array(
									'key' => 'field_5d7755f421d61',
									'label' => 'Internal link',
									'name' => 'internal_link',
									'type' => 'post_object',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5d77ea80eef62',
												'operator' => '!=',
												'value' => '1',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'post_type' => array(
										0 => 'page',
									),
									'taxonomy' => '',
									'allow_null' => 0,
									'multiple' => 0,
									'return_format' => 'object',
									'acfe_bidirectional' => array(
										'acfe_bidirectional_enabled' => '0',
									),
									'acfe_validate' => '',
									'acfe_update' => '',
									'ui' => 1,
								),
								array(
									'key' => 'field_5d77eac1eef63',
									'label' => 'External link',
									'name' => 'external_link',
									'type' => 'link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5d77ea80eef62',
												'operator' => '==',
												'value' => '1',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'return_format' => 'array',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_thumbnail' => '2620',
					'acfe_flexible_category' => 'Sidebar',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
				),
			),
			'button_label' => 'Add module',
			'min' => 0,
			'max' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'cpt_sidebar_content',
			),
		),
	),
	'menu_order' => 36,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'discussion',
		3 => 'comments',
		4 => 'author',
		5 => 'format',
		6 => 'page_attributes',
		7 => 'featured_image',
		8 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_permissions' => '',
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1611658182,
));

endif;